# Generated by Django 4.2.7 on 2023-11-29 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['created_on']},
        ),
        migrations.RenameField(
            model_name='post',
            old_name='create_on',
            new_name='created_on',
        ),
    ]
